### Modules
1. pre-defines modules
2. user defined modules

In [2]:
import string
string.digits

'0123456789'

In [3]:
import string as s # alias naming the function import module as alias name
s.digits

'0123456789'

In [10]:
from string import digits,punctuation 
print(digits)
print(punctuation)

0123456789
!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


In [12]:
from string import * # * to import all the contents of the modules

print(digits)
print(punctuation)

0123456789
!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


### user defined modules

In [8]:
import operations as o
o.wish("karthik")

good afternoon karthik


In [9]:
o.add(10,20)

30

In [10]:
o.sub(20,10)

10

In [11]:
o.mul(20,30)

600

In [12]:
o.exp(2,3)

8

### Built in libraries :
1. math
2. statistics

In [15]:
import math 

In [16]:
math.factorial(5)

120

In [24]:
#using math mod find out the area of the circle
import math
def Area(r):
    return math.pi*(r**2)
Area(7)    

153.93804002589985

In [30]:
import statistics as stats
list1 = list(range(1,21))
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [31]:
print(stats.mean(list1))
print(sum(list1)/len(list1))

10.5
10.5


In [32]:
print(stats.median(list1))

10.5


In [33]:
list2=[10,20,30,40,50,10,10,20,30]
print(stats.mode(list2))

10


In [36]:
help("statistics")

Help on module statistics:

NAME
    statistics - Basic statistics module.

DESCRIPTION
    This module provides functions for calculating statistics of data, including
    averages, variance, and standard deviation.
    
    Calculating averages
    --------------------
    
    ==================  =============================================
    Function            Description
    ==================  =============================================
    mean                Arithmetic mean (average) of data.
    harmonic_mean       Harmonic mean of data.
    median              Median (middle value) of data.
    median_low          Low median of data.
    median_high         High median of data.
    median_grouped      Median, or 50th percentile, of grouped data.
    mode                Mode (most common value) of data.
    ==================  =============================================
    
    Calculate the arithmetic mean ("the average") of data:
    
    >>> mean([-1.0, 2.5, 3.25, 

In [37]:
stats.stdev(list2)

14.240006242195886

In [38]:
stats.variance(list2)

202.77777777777777

### random
1. randint() -->start and stop value,start and stop values are inc
2. randrange() --> start and stop to exclude the stop value
3. random()-->generate a floationg point number
4. choice()-->gives single element
5. choices()-->gives multiple elements

In [119]:
import random as r
print(r.randint(1, 10))
print(r.randrange(1, 10))
print(r.choice(list2))
print(r.choices(list1,k=3))
print(r.random())

2
8
30
[16, 4, 15]
0.06246081341500198


### os:
1. rename()
2. remove()
3. mkdir()-->mainkg a directory
4. getcwd()-->to get current working directory
5. listdir()--> list of things
6. chdir()--> changing to toher directory
7. rmdir()--> remove directory

In [1]:
import os
os.mkdir("sample3")


In [125]:
os.getcwd()

'C:\\Users\\karthik\\desktop\\AI and ML'

In [126]:
os.listdir()

['.ipynb_checkpoints',
 '01-06-2020.ipynb',
 '02-06-2020.ipynb',
 '03-06-2020.ipynb',
 '27-05-2020.ipynb',
 '28-05-2020.ipynb',
 '29-05-2020.ipynb',
 '30-05-2020.ipynb',
 'Assignment1 (27.05.2020).ipynb',
 'assignments',
 'commandsday1.txt',
 'data.txt',
 'folder1',
 'hello',
 'operations.py',
 'sample2',
 'sample3',
 '__pycache__']

In [133]:
os.chdir("C:\\Users\\karthik\\desktop\\AI and ML\\sample3")

In [129]:
os.getcwd()

'C:\\Users\\karthik\\desktop\\AI and ML\\sample3'

In [134]:
os.chdir("C:\\Users\\karthik\\desktop\\AI and ML")

In [2]:
os.rmdir("sample3")

### Numpy Packages
1. operations relatied to numerics
2. computational operations

In [4]:
import numpy as ny
list1=[1,2,3,4,5]
arr1 = ny.array(list1)
print(arr1,type(arr1))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [6]:
list2=list(range(1,101))
print(list2,end=" ")

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100] 

In [10]:
arr2 = np.arange(1,101)
arr2

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

### differences between python list and numpy arrays
1. numpy arrays occupyes less memory as compared to lists
2. numpy is fast 
3. numpy is more convenient 

In [15]:
import sys
size=1000
list1=list(range(size))
print(sys.getsizeof(list1[0]))#size of each element
print(sys.getsizeof(list1[0])*size)#size of tthe entire list 
arr1=np.arange(1000)
print(arr1.itemsize)
print(arr1.itemsize*arr1.size)

24
24000
4
4000


In [58]:
import time
size=100000
list1 = list(range(size))
list2 = list(range(size))
start=time.time
result=[x+y for x,y in zip(list1,list2)]
print("time for pyhton list",time.time()-start())

arr1 = np.arange(size)
arr2 = np.arange(size)
result = arr1+arr2
print("time for numpy list",time.time()-start())

time for pyhton list 0.0
time for numpy list 0.0


In [20]:
l1=[1,2,3,4,5]
l2=[1,2,3,4,5]
print([x+y for x,y in zip(l1,l2)])

[2, 4, 6, 8, 10]


In [63]:
a1=[1,2,3,4,5]
a2=[1,2,3,4,5]
arr1=np.array(a1)
arr2=np.array(a2)
print(arr1+arr2)

[ 2  4  6  8 10]
