### Modules --> pre-defined,user-defined
.  predefined : math,os,random,string,statistics
.  user-defines:
modules
### The different ways of importing the modules : 
1. import modulename
2. import modulename as alias_name
3. from module import .......
4. from module import *
 

### Nine lives

In [1]:
import random
import string
lives=9
hearts="\u2764"
words=['pizza','final','globe','apple','blind','birth','coach','minus','paper','royal']
secret_word=random.choice(words)
clue=list('?????')
lives_symbol='L'
guessed_word_correctly=False
def update_clue(guessed_letter,secret_word,clue):
    index=0
    while index<len(secret_word):
        if guessed_letter==secret_word[index]:
            clue[index]=guessed_letter
        index=index+1

while lives>0:
    print(clue)
    print("lives left:",hearts*lives)
    guess=input("guess a letter or whole word :")
    if guess==secret_word:
        guessed_word_correctly=True
        break
    if guess in secret_word:
        update_clue(guess,secret_word,clue)
    else:
        print("you lost a life!")
        lives=lives-1
if guessed_word_correctly == True:
    print("you won and secret word is:",secret_word)
else:
    print("you lost and secret word is:",secret_word)


['?', '?', '?', '?', '?']
lives left: ❤❤❤❤❤❤❤❤❤
guess a letter or whole word :a
['?', '?', '?', 'a', '?']
lives left: ❤❤❤❤❤❤❤❤❤
guess a letter or whole word :f
you lost a life!
['?', '?', '?', 'a', '?']
lives left: ❤❤❤❤❤❤❤❤
guess a letter or whole word :c
you lost a life!
['?', '?', '?', 'a', '?']
lives left: ❤❤❤❤❤❤❤
guess a letter or whole word :r
['r', '?', '?', 'a', '?']
lives left: ❤❤❤❤❤❤❤
guess a letter or whole word :o
['r', 'o', '?', 'a', '?']
lives left: ❤❤❤❤❤❤❤
guess a letter or whole word :y
['r', 'o', 'y', 'a', '?']
lives left: ❤❤❤❤❤❤❤
guess a letter or whole word :a
['r', 'o', 'y', 'a', '?']
lives left: ❤❤❤❤❤❤❤
guess a letter or whole word :l
['r', 'o', 'y', 'a', 'l']
lives left: ❤❤❤❤❤❤❤
guess a letter or whole word :royal
you won and secret word is: royal
royal


### Numpy package:
1. Numerical data
2. computations on numberics

In [3]:
import numpy as np

### differences between numpy array and lists
1. memory
2. fast
3. 

In [6]:
#1-d array
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [9]:
a1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
a1.ndim #to find the dimentions of the array

2

In [11]:
a1.shape

(3, 3)

In [12]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a2.shape[0]) #when the value is 0 its rows
print(a2.shape[1]) #when the value is 1 its columns

(4, 3)

In [15]:
a3=np.array([10,11,12,13])
a4=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a3.ndim)
print(a4.ndim)

1
2


In [30]:
#inserting the elements dynamically
a3=np.array([],dtype='int')
a3=np.append(a3,int(input()))#it needs 2 values to which array we want to add and the values
a3

15


array([15])

In [31]:
a3=np.append(a3,[10,20,30,40,50])
a3

array([15, 10, 20, 30, 40, 50])

In [33]:
a2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### slicing:

In [34]:
print(a3[3])

30


In [37]:
print(a2[1,1])

5


In [41]:
print(a2[2:,:])

[[ 7  8  9]
 [10 11 12]]


In [43]:
print(a2[2:,0:2])

[[ 7  8]
 [10 11]]


In [45]:
print(a2[2:,1:4])

[[ 8  9]
 [11 12]]


In [46]:
print(a2[0,0:2])

[1 2]


In [50]:
print(a2[1,0:4])

[4 5 6]


In [51]:
print(a2[0:4:3,])

[[ 1  2  3]
 [10 11 12]]


### Array iterations

In [67]:
for row in a2:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [69]:
#to iterate through the elements one by one
for ele in a2.flat:
    print(ele,end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 

In [71]:
np.array(a2.flat)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### Indexing with boolean array

In [76]:
arr1 = np.arange(1,21)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [77]:
arr1 = np.arange(1,21).reshape(5,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [79]:
# to extract the even numbers from the array 
result =(arr1 % 2 == 0)
result

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [88]:
arr1[result]
array1=arr1[result]
arr2= array1.reshape(5,2)
arr2

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16],
       [18, 20]])

### Appending Array

In [91]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(11,20).reshape(3,3)
print(np.vstack((arr1,arr2)))# vertical stacking

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


In [92]:
print(np.hstack((arr1,arr2)))#horizontal stacking 

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


### Attributes
1. size
2. itemsize
3. dtype
4. ndim
5. shape

In [94]:
arr = np.arange(1,11).reshape(2,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [95]:
print(arr.size)
print(arr.itemsize)
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

10
4
int32
2
(2, 5)


### Functions:
1. zeros()
2. ones()
3. full()
4. eye()
5. linspace()
6. arange()
7. reshape()
8. ravel()

In [98]:
np.zeros((2,3),dtype="int32")

array([[0, 0, 0],
       [0, 0, 0]])

In [99]:
np.ones((2,3),dtype="int32")

array([[1, 1, 1],
       [1, 1, 1]])

In [105]:
#full
f=np.full((2,2),"karthik")
print(f)

[['karthik' 'karthik']
 ['karthik' 'karthik']]


In [106]:
#eye
e=np.eye(3,dtype="int32")
e

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [108]:
#linspace() -- > linear spacing elements will be returned
l=np.linspace(1,10,5)
l

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [112]:
#ravel()
print(np.array(a.flat))
print(a.ravel())

[1 2 3 4 5]
[1 2 3 4 5]


### Fucntion:
1. min()
2. max
3. sum()
4. sqrt()
5. mean()
6. median()
7. std()

In [117]:
print(a.min())
print(a.max())
print(a)


1
5
[1 2 3 4 5]


In [116]:
print(a.sum())
print(a.sum(axis=1))#sum of row elements
print(a.sum(axis=0))#sum of column elements 

15


AxisError: axis 1 is out of bounds for array of dimension 1

In [118]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [120]:
np.mean(a)

3.0

In [121]:
np.median(a)

3.0

In [122]:
np.std(a)

1.4142135623730951

### Mathematical operations: ```+,-,*,/,%```


In [136]:
arr1=np.arange(1,11)
arr2=np.arange(11,21)
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr1%arr2)


[12 14 16 18 20 22 24 26 28 30]
[-10 -10 -10 -10 -10 -10 -10 -10 -10 -10]
[ 11  24  39  56  75  96 119 144 171 200]
[0.09090909 0.16666667 0.23076923 0.28571429 0.33333333 0.375
 0.41176471 0.44444444 0.47368421 0.5       ]
[ 1  2  3  4  5  6  7  8  9 10]


### dor() --> matrix multiplication
### arr1= m*n
### arr2=n*i

In [142]:
arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(11,20).reshape(3,3)
print(arr1.dot(arr2))

[[ 90  96 102]
 [216 231 246]
 [342 366 390]]


In [143]:
#transpose of an array
arr1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### Applying user defined functions:

In [147]:
list1 = list(range(1,20))
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [153]:
a=np.array(list1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [151]:
# 1/(1+1) -->x/(x+1)
result=[x/(x+1) for x in list1]
result

[0.5,
 0.6666666666666666,
 0.75,
 0.8,
 0.8333333333333334,
 0.8571428571428571,
 0.875,
 0.8888888888888888,
 0.9,
 0.9090909090909091,
 0.9166666666666666,
 0.9230769230769231,
 0.9285714285714286,
 0.9333333333333333,
 0.9375,
 0.9411764705882353,
 0.9444444444444444,
 0.9473684210526315,
 0.95]

In [155]:
f=np.vectorize(lambda x : x/(x+1))
f(a)

array([0.5       , 0.66666667, 0.75      , 0.8       , 0.83333333,
       0.85714286, 0.875     , 0.88888889, 0.9       , 0.90909091,
       0.91666667, 0.92307692, 0.92857143, 0.93333333, 0.9375    ,
       0.94117647, 0.94444444, 0.94736842, 0.95      ])

In [157]:
C = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n']

s = []

for i in range(3):

    s.append(C[i::3])

print(s)



[['a', 'd', 'g', 'j', 'm'], ['b', 'e', 'h', 'k', 'n'], ['c', 'f', 'i', 'l']]


In [159]:
import random
random

True
