In [5]:
from numpy import random
print(random.randint(1,100))#random integerin the given array
print(random.rand())#flolating point value between 0-1

21
0.12317029907600807


In [11]:
print(random.randint(100,size=(3)))
print("\n",random.randint(100,size=(3,3)))
print("\n", random.randint(100,size=(3,3,2)))

[17 39 95]

 [[99 48 10]
 [87  2 68]
 [90  1 86]]

 [[[47 91]
  [16 93]
  [37 51]]

 [[43 14]
  [59 71]
  [26 29]]

 [[ 9 12]
  [29 49]
  [73  0]]]


In [13]:
print("\n",random.rand())
print("\n",random.rand(3))
print("\n",random.rand(3,3,2))


 0.0573934263694561

 [0.20661988 0.09123634 0.44780391]

 [[[0.14750165 0.97702825]
  [0.85058735 0.75808819]
  [0.54402829 0.35204996]]

 [[0.8465256  0.75778756]
  [0.09157477 0.35723951]
  [0.14373172 0.40231012]]

 [[0.54332555 0.30211283]
  [0.85023665 0.79336868]
  [0.24481612 0.20495994]]]


In [16]:
a=random.randint(100,size=(3,3)).ravel()
print(a)

[56 47 50 89 26 78 20 59 93]


In [17]:
#to gen a single list
random.choice(a)

59

In [43]:
#to gen a array from the list of elements 
print(random.choice((a),size=(3,4)))

[[89 26 93 47]
 [20 78 93 26]
 [26 56 59 89]]


In [93]:
print(random.choice([1,2,3,4,5,6],size=(3,4)))

[[1 3 1 3]
 [2 1 4 1]
 [3 6 4 5]]


### Pandas:
1. data manipulations,analysis amd deleting
2. tabular,unlabelled

### creating a data frame
1. using 2 dictionaries
2. using a simple dictionary
3. using series

In [117]:
# creating a data frame using 2 dictionaried
import pandas as pd
import numpy as np
dict1={"a":1,"b":2,"c":3,"d":4,"e":5}
dict2={"a":5,"b":6,"c":7,"d":8,"e":9}
data = {"first":dict1,"second":dict2}
df= pd.DataFrame(data,dtype=np.int64)
df
# Nan means not a number

first  second
a      1       5
b      2       6
c      3       7
d      4       8
e      5       9

In [124]:
#simple dictionary
d1={"names":["srinija","karthik","vardhan","sowmya"],"address":["hyd","hyd","hyd","hyd"]}
df1=pd.DataFrame(d1)
df1

names address
0  srinija     hyd
1  karthik     hyd
2  vardhan     hyd
3   sowmya     hyd

In [256]:
# using series
s1 = pd.Series([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
s2=pd.Series([11,12,13,14,15,16,17,18,19,20])
s3=pd.Series(['a','b','c','d','e','f','g','h','i','j'])
data1={"column1":s1,"column2":s2,"column3":s3}
df2=pd.DataFrame(data1)
df2

column1  column2 column3
0         1     11.0       a
1         2     12.0       b
2         3     13.0       c
3         4     14.0       d
4         5     15.0       e
5         6     16.0       f
6         7     17.0       g
7         8     18.0       h
8         9     19.0       i
9        10     20.0       j
10       11      NaN     NaN
11       12      NaN     NaN
12       13      NaN     NaN
13       14      NaN     NaN
14       15      NaN     NaN
15       16      NaN     NaN

### selecting the data from the data frame:
1. loc
2. iloc

In [257]:
df2["column2"]

0     11.0
1     12.0
2     13.0
3     14.0
4     15.0
5     16.0
6     17.0
7     18.0
8     19.0
9     20.0
10     NaN
11     NaN
12     NaN
13     NaN
14     NaN
15     NaN
Name: column2, dtype: float64

In [258]:
type(df2)

pandas.core.frame.DataFrame

In [259]:
df2[["column2","column3"]]

column2 column3
0      11.0       a
1      12.0       b
2      13.0       c
3      14.0       d
4      15.0       e
5      16.0       f
6      17.0       g
7      18.0       h
8      19.0       i
9      20.0       j
10      NaN     NaN
11      NaN     NaN
12      NaN     NaN
13      NaN     NaN
14      NaN     NaN
15      NaN     NaN

In [260]:
df2.loc[1:10,["column1","column2"]]

column1  column2
1         2     12.0
2         3     13.0
3         4     14.0
4         5     15.0
5         6     16.0
6         7     17.0
7         8     18.0
8         9     19.0
9        10     20.0
10       11      NaN

In [261]:
df2.iloc[:,1]

0     11.0
1     12.0
2     13.0
3     14.0
4     15.0
5     16.0
6     17.0
7     18.0
8     19.0
9     20.0
10     NaN
11     NaN
12     NaN
13     NaN
14     NaN
15     NaN
Name: column2, dtype: float64

In [262]:
df2.loc[1:4,["column1","column2"]]

column1  column2
1        2     12.0
2        3     13.0
3        4     14.0
4        5     15.0

In [263]:
df2.iloc[1:4,0:2]

column1  column2
1        2     12.0
2        3     13.0
3        4     14.0

### retriving the information from the data frame 

In [264]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   column1  16 non-null     int64  
 1   column2  10 non-null     float64
 2   column3  10 non-null     object 
dtypes: float64(1), int64(1), object(1)
memory usage: 512.0+ bytes


In [265]:
df2.shape

(16, 3)

In [266]:
df2.columns

Index(['column1', 'column2', 'column3'], dtype='object')

In [267]:
df2.index

RangeIndex(start=0, stop=16, step=1)

### viewing data from the data frame:
1. head()
2. tail()
3. sample()

In [298]:
df2.head()#if nothing is given it returns 5 rows

column1  column2 column3
0        1     11.0       a
1        2     12.0       b
2        3     13.0       c
3        4     14.0       d
4        5     15.0       e

In [300]:
df2.head(3)#it now reutrns 3 rows

column1  column2 column3
0        1     11.0       a
1        2     12.0       b
2        3     13.0       c

In [271]:
df2.head(6)

column1  column2 column3
0        1     11.0       a
1        2     12.0       b
2        3     13.0       c
3        4     14.0       d
4        5     15.0       e
5        6     16.0       f

In [275]:
df2.tail()

column1  column2 column3
11       12      NaN     NaN
12       13      NaN     NaN
13       14      NaN     NaN
14       15      NaN     NaN
15       16      NaN     NaN

In [278]:
df2.tail(2)

column1  column2 column3
14       15      NaN     NaN
15       16      NaN     NaN

In [328]:
df2.sample()

column1  column2 column3
14       15      NaN     NaN

In [327]:
df2.sample(3)

column1  column2 column3
9       10     20.0       j
1        2     12.0       b
3        4     14.0       d

In [329]:
df2.describe()

column1   column2
count  16.000000  10.00000
mean    8.500000  15.50000
std     4.760952   3.02765
min     1.000000  11.00000
25%     4.750000  13.25000
50%     8.500000  15.50000
75%    12.250000  17.75000
max    16.000000  20.00000

In [331]:
#changin the column names
df2=df2.rename(columns={"column1":"first","column2":"second","column3":"third"})
df2

first  second third
0       1    11.0     a
1       2    12.0     b
2       3    13.0     c
3       4    14.0     d
4       5    15.0     e
5       6    16.0     f
6       7    17.0     g
7       8    18.0     h
8       9    19.0     i
9      10    20.0     j
10     11     NaN   NaN
11     12     NaN   NaN
12     13     NaN   NaN
13     14     NaN   NaN
14     15     NaN   NaN
15     16     NaN   NaN